language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before install:
  - chmod +x build.sh
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: ./build.sh

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - sechiyo97@daum.net